language: cpp
compiler:
- gcc
- clang
env:
  global:
  - APT_DEPENDENCIES="doxygen doxygen-latex libltdl-dev libboost-all-dev liblog4cxx10-dev coinor-libipopt-dev libblas-dev liblapack-dev libmumps-seq-dev gfortran"
  - GIT_DEPENDENCIES="roboptim/roboptim-core roboptim/roboptim-core-plugin-ipopt"
  - DEBSIGN_KEYID=5AE5CD75
  - PPA_URI="roboptim/ppa"
  - NSIQCPPSTYLE_FILEFILTERPATH=cmake/filefilter.txt
  - GH_USERNAME=thomas-moulard
  - GH_REPO=roboptim/roboptim-trajectory
  - secure: dn2Iai0VINXoHlHTL0s0/+37pIbTTaKI0698dAPYpMBUkE9RIuumcKEjDP1uKqaA9anSPm1dLrtSsSm+kFGaEBk+cviGxsc242KSxqxCBqNP3Bbm4dFCbKnnG4c7I8OTuYUuJJg90xVm2QGAnUNn9vvBnydvTpeCEN850lT+dBM=
  - secure: qFCzChpnDkG00gsaRzNmjbWyBzEaHutoM6BUsm9jxH2BlvDRLQUN/WxVmmIKKB9t8y3d2jPp4zRJiTqTUTJo3DaUuc/5s5XZKEqmL1YgIP+UbIWJpDNaun9EpA2YJxoFatYzun6X1FKm2D7WMSVXatKyRDh1bEVaoW8tqI6Vwq0=
  - secure: GwtCk4WjcY6iyQxmVD4YQ2NkEP7H/zdBv2144UNtLe6jaLxwFsDt0n9mNIela/bCyEq2GQsjI3QofbFol5EAMhv1Dm93mLYsyWCGNcZrRN/OwfjluMcBlq5WMETbYXl/009kw3lxXWddNBHTR6QCEAlnZ9fUmj+3diy/UVvW74c=
notifications:
  email: roboptim@googlegroups.com
  hipchat:
    rooms:
      secure: X+ZM9zdIE0uAXC6FcGszec+DYxgzkuNkwmDJmofwbTFFhzhoWQxu2EbvGnyBe06MVRzlfIisWBXUgln/dCxMTqbXy0jFxU5L2clQawUXQFtD17hgjeQ1ZO6wdBXqfFTbh1oWr6yKEvz1q2EE6FVEXGllejVVC4HTkynZPSFsukI=
before_install:
- ./.travis/dependencies/eigen-3.2.0
- ./.travis/run  before_install
script: ./.travis/run build
after_failure: ./.travis/run after_failure
after_success: ./.travis/run after_success
branches:
  only:
  - master
  - debian
matrix:
  allow_failures:
  - compiler: clang
